Fantom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("posts.urls")),
    path("users/", include("users.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from posts.views import *


urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("detail/<int:pk>/<slug:slug>", PostDetail.as_view(), name="detail"),
    path("category/<int:pk>/<slug:slug>", CategoryDetail.as_view(), name="category_detail"),
    path("tag/<slug:slug>", TagDetail.as_view(), name="tag_detail"),
    path("create-post/", CreatePostView.as_view(), name="create_post"),
    path("update-post/<int:pk>/<slug:slug>", UpdatePostView.as_view(), name="update_post"),
    path("delete-post/<int:pk>/<slug:slug>", DeletePostView.as_view(), name="delete_post"),
    path("search/", SearchView.as_view(), name="search")
]

users/urls.py
from django.urls import path
from users.views import *
from django.contrib.auth import views as authView


app_name = "users"

urlpatterns = [
    path("", UserListView.as_view(), name="users_list"),
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", UserLoginView.as_view(), name="login"),
    path("logout/", UserLogoutView.as_view(), name="logout"),
    path("password-change/", authView.PasswordChangeView.as_view(), name="password_change"),
    path("password-change-done/", authView.PasswordChangeDoneView.as_view(), name="password_change_done"),
    path("update-profile/<slug:slug>/", UserUpdateProfileView.as_view(), name="update_profile"),
    path("profile/", UserProfileView.as_view(), name="profile"),
    path("posts/<int:pk>/", UserPostView.as_view(), name="user_posts")
]

users/models.py
from django.db import models
from django.conf import settings
from django.template.defaultfilters import slugify
from PIL import Image
from django.db.models.signals import post_save


class UserProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    birth_day = models.DateField(null=True, blank=True)
    bio = models.TextField(max_length=1000, blank=True)
    image = models.ImageField(default="users/profile-pic.png", blank=True, null=True, upload_to="users")
    slug = models.SlugField(editable=False)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.user.username)
        super(UserProfile, self).save(*args, **kwargs)

        img = Image.open(self.image.path)
        if img.height > 200 or img.width > 200:
            new_size = (200, 200)
            img.thumbnail(new_size)
            img.save(self.image.path)
    
    def __str__(self):
        return self.user.username


def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)


post_save.connect(create_user_profile, sender=settings.AUTH_USER_MODEL)

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Field, Layout
from users.models import UserProfile


class RegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=200)
    last_name = forms.CharField(max_length=200)
    username = forms.CharField(max_length=200)
    email = forms.EmailField(max_length=200)
    password1 = forms.CharField()
    password2 = forms.CharField()

    class Meta(UserCreationForm):
        model = User
        fields = ("username", "first_name", "last_name", "email", "password1", "password2")


class UserProfileForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_method = "post"
        self.helper.field_class = "mt-10"
        self.helper.layout = Layout(
            Field("birth_day", css_class="single-input"),
            Field("bio", css_class="single-input"),
            Field("image", css_class="single-input"),
        )

        self.helper.add_input(Submit("submit", "Update", css_class="primary-btn submit_btn"))


    class Meta:
        model = UserProfile
        fields = ("birth_day", "bio", "image")
        widgets = {
            "birth_day": forms.DateInput(attrs={"type": "date"})
        }

users/views.py
from django.views.generic import CreateView, UpdateView, ListView
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from users.forms import RegisterForm
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from users.models import UserProfile
from posts.models import Post
from users.forms import UserProfileForm


class RegisterView(CreateView):
    template_name = "users/register.html"
    form_class = RegisterForm
    success_url = "/"


class UserLoginView(LoginView):
    template_name = "users/login.html"

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect("/")
        return super(UserLoginView, self).dispatch(request, *args, **kwargs)


class UserLogoutView(LogoutView):
    template_name = "users/login.html"


class UserUpdateProfileView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = UserProfile
    template_name = "users/profile-update.html"
    form_class = UserProfileForm
    success_message = "Your profile has been updated."

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.save()
        return super(UserUpdateProfileView, self).form_valid(form)
    
    def get_success_url(self):
        return reverse_lazy("users:update_profile", kwargs={"slug": self.object.slug})
    
    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.user != request.user:
            return HttpResponseRedirect("/")
        
        return super(UserUpdateProfileView, self).get(request, *args, **kwargs)


class UserProfileView(LoginRequiredMixin, ListView):
    model = Post
    template_name = "users/profile.html"
    context_object_name = "posts"
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super(UserProfileView, self).get_context_data(**kwargs)
        context["profile"] = UserProfile.objects.get(user=self.request.user)
        return context
    
    def get_queryset(self):
        return Post.objects.filter(user=self.request.user).order_by("-id")


class UserPostView(ListView):
    template_name = "users/user-post.html"
    model = Post
    context_object_name = "posts"
    paginate_by = 5

    def get_queryset(self):
        return Post.objects.filter(user=self.kwargs["pk"])


class UserListView(ListView):
    template_name = "users/user-list.html"
    model = UserProfile
    context_object_name = "profiles"
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super(UserListView, self).get_context_data(**kwargs)
        return context

templates/users/login.html
{% extends "base.html" %}

<!--  -->

{% load static %}

<!--  -->

{% block content %}

<!--================Home Banner Area =================-->
<section class="banner_area">
  <div class="banner_inner d-flex align-items-center">
    <div
      class="overlay bg-parallax"
      data-stellar-ratio="0.9"
      data-stellar-vertical-offset="0"
      data-background=""
    ></div>
    <div class="container">
      <div class="banner_content text-center">
        <h2>Login</h2>
        <div class="page_link">
          <a href="{% url 'index' %}">Home</a>
        </div>
      </div>
    </div>
  </div>
</section>
<!--================End Home Banner Area =================-->

<!--================Blog Area =================-->
<section class="blog_area p_100">
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
        {% if not user.is_authenticated %}
        <h2>Login</h2>
        <div class="blog_left_sidebar">
          <!-- form -->
          <form action="" method="post">
            {% csrf_token %}

            <!-- errors  -->
            {% if form.errors %}
            <div id="errors">
              <div class="inner">
                <p style="color: red">Please correct the errors below</p>
                <ul>
                  {% for field in form %}
                  <!--  -->
                  {% if field.errors %}
                  <li>{{form.label}} : {{field.errors|striptags}}</li>
                  {% endif %}
                  <!--  -->
                  {% endfor %}
                </ul>
              </div>
            </div>
            {% endif %}
            <!-- end errors  -->

            <!-- username -->
            <div class="mt-10">
              <input
                type="text"
                name="username"
                placeholder="Username"
                onfocus="this.placeholder = ''"
                onblur="this.placeholder = 'Username'"
                required=""
                class="single-input"
              />
            </div>

            <!-- password1 -->
            <div class="mt-10">
              <input
                type="password"
                name="password"
                placeholder="Password"
                onfocus="this.placeholder = ''"
                onblur="this.placeholder = 'Password'"
                required=""
                class="single-input"
              />
            </div>

            <!-- submit button -->
            <input
              type="submit"
              value="Login"
              class="genric-btn success-border circle"
              style="margin-top: 1rem"
            />
          </form>
          <!-- end form -->
        </div>

        {% else %}
        <h2>You have logged in</h2>
        {% endif %}
      </div>
      <div class="col-lg-4">{% include 'right-sidebar.html' %}</div>
    </div>
  </div>
</section>
<!--================Blog Area =================-->

{% endblock %}

templates/users/profile-update.html
{% extends "base.html" %}

<!--  -->

{% load static %}

<!--  -->

{% load crispy_forms_tags %}

<!--  -->

{% block content %}

<!--================Home Banner Area =================-->
<section class="banner_area">
  <div class="banner_inner d-flex align-items-center">
    <div class="overlay bg-parallax" data-stellar-ratio="0.9" data-stellar-vertical-offset="0" data-background=""></div>
    <div class="container">
      <div class="banner_content text-center">
        <h2>Update Profile</h2>
        <div class="page_link">
          <a href="{% url 'index' %}">Home</a>
        </div>
      </div>
    </div>
  </div>
</section>
<!--================End Home Banner Area =================-->

<!--================Blog Area =================-->
<section class="blog_area p_100">
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
        <h2>Update Profile</h2>
        <div class="blog_left_sidebar">
          <!-- form -->
          {% crispy form %}
          <!-- end form -->
        </div>
      </div>
      <div class="col-lg-4">{% include 'right-sidebar.html' %}</div>
    </div>
  </div>
</section>
<!--================Blog Area =================-->

{% endblock %}

templates/users/profile.html
{% extends "base.html" %}

<!--  -->

{% load static %}

<!--  -->

{% block content %}

<!--================Home Banner Area =================-->
<section class="banner_area">
  <div class="banner_inner d-flex align-items-center">
    <div class="overlay bg-parallax" data-stellar-ratio="0.9" data-stellar-vertical-offset="0" data-background=""></div>
    <div class="container">
      <div class="banner_content text-center">
        <h2>Profile</h2>
        <div class="page_link">
          <img src="{{ profile.image.url }}" alt="" />
          <h4 style="color: white"><strong>First Name : </strong>{{profile.user.first_name}}</h4>
          <h4 style="color: white"><strong>Last Name : </strong>{{profile.user.last_name}}</h4>
          <h4 style="color: white"><strong>Username : </strong>{{profile.user.username|title}}</h4>
          <h4 style="color: white"><strong>Email : </strong>{{profile.user.email}}</h4>
          <h4 style="color: white"><strong>Birth Day : </strong>{{profile.birth_day}}</h4>
          <h4 style="color: white"><strong>About Me : </strong>{{profile.bio|linebreaks}}</h4>
        </div>
      </div>
    </div>
  </div>
</section>
<!--================End Home Banner Area =================-->

<!--================Blog Area =================-->
<section class="blog_area p_120">
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
        <div class="blog_left_sidebar">
          <!-- posts -->
          {% for post in posts %}
          <article class="blog_style1">
            <div class="blog_img">
              <img class="img-fluid" src="{{post.image.url}}" alt="" />
            </div>
            <div class="blog_text">
              <div class="blog_text_inner">
                {% for tag in post.tag.all %}
                <a class="cat" href="{% url 'tag_detail' slug=tag.slug %}">{{tag.title}}</a>
                {% endfor %}
                <a href="{% url 'detail' pk=post.id slug=post.slug %}"><h4>{{post.title}}</h4></a>
                <p>{{post.content|truncatechars:150}}</p>
                <div class="date">
                  <a href="#"
                    ><i class="fa fa-calendar" aria-hidden="true"></i>
                    {{post.publishing_date}}
                  </a>
                  <a href="#"><i class="fa fa-comments-o" aria-hidden="true"></i> 05</a>
                </div>
              </div>
            </div>
          </article>
          {% endfor %}
          <!-- end posts -->

          <!-- pagination -->
          {% if is_paginated %}
          <nav class="blog-pagination justify-content-center d-flex">
            <ul class="pagination">
              <!-- previous -->
              {% if page_obj.has_previous %}
              <li class="page-item">
                <a href="?page={{page_obj.previous_page_number}}" class="page-link" aria-label="Previous">
                  <span aria-hidden="true">
                    <span class="lnr lnr-chevron-left"></span>
                  </span>
                </a>
              </li>
              {% else %}
              <li class="page-item disabled">
                <a href="#" class="page-link" aria-label="Previous">
                  <span aria-hidden="true">
                    <span class="lnr lnr-chevron-left"></span>
                  </span>
                </a>
              </li>
              {% endif %}
              <!-- end previous -->

              <!-- pages -->
              {% for i in paginator.page_range%}
              <!--  -->
              {% if page_obj.number == i %}
              <li class="page-item active">
                <a href="#" class="page-link">{{ i }}</a>
              </li>
              {% else %}

              <li class="page-item">
                <a href="?page={{i}}" class="page-link">{{ i }}</a>
              </li>
              {% endif %}
              <!--  -->
              {% endfor %}
              <!-- end pages -->

              <!-- next page -->
              {% if page_obj.has_next %}
              <li class="page-item">
                <a href="?page={{page_obj.next_page_number}}" class="page-link" aria-label="Next">
                  <span aria-hidden="true">
                    <span class="lnr lnr-chevron-right"></span>
                  </span>
                </a>
              </li>
              {% else %}
              <li class="page-item disabled">
                <a href="#" class="page-link" aria-label="Next">
                  <span aria-hidden="true">
                    <span class="lnr lnr-chevron-right"></span>
                  </span>
                </a>
              </li>
              {% endif %}
              <!-- end next page -->
            </ul>
          </nav>
          {% endif %}
          <!-- end pagination -->
        </div>
      </div>
      <div class="col-lg-4">{% include 'right-sidebar.html' %}</div>
    </div>
  </div>
</section>
<!--================Blog Area =================-->

{% endblock %}

templates/users/register.html
{% extends "base.html" %}

<!--  -->

{% load static %}

<!--  -->

{% block content %}

<!--================Home Banner Area =================-->
<section class="banner_area">
  <div class="banner_inner d-flex align-items-center">
    <div
      class="overlay bg-parallax"
      data-stellar-ratio="0.9"
      data-stellar-vertical-offset="0"
      data-background=""
    ></div>
    <div class="container">
      <div class="banner_content text-center">
        <h2>Register</h2>
        <div class="page_link">
          <a href="{% url 'index' %}">Home</a>
        </div>
      </div>
    </div>
  </div>
</section>
<!--================End Home Banner Area =================-->

<!--================Blog Area =================-->
<section class="blog_area p_100">
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
        <h2>Create New Account</h2>
        <div class="blog_left_sidebar">
          <!-- form -->
          <form action="" method="post">
            {% csrf_token %}

            <!-- errors  -->
            {% if form.errors %}
            <div id="errors">
              <div class="inner">
                <p style="color: red">Please correct the errors below</p>
                <ul>
                  {% for field in form %}
                  <!--  -->
                  {% if field.errors %}
                  <li>{{form.label}} : {{field.errors|striptags}}</li>
                  {% endif %}
                  <!--  -->
                  {% endfor %}
                </ul>
              </div>
            </div>
            {% endif %}
            <!-- end errors  -->

            <!-- first name -->
            <div class="mt-10">
              <input
                type="text"
                name="first_name"
                placeholder="First Name"
                onfocus="this.placeholder = ''"
                onblur="this.placeholder = 'First Name'"
                required=""
                class="single-input"
              />
            </div>

            <!-- last name -->
            <div class="mt-10">
              <input
                type="text"
                name="last_name"
                placeholder="Last Name"
                onfocus="this.placeholder = ''"
                onblur="this.placeholder = 'Last Name'"
                required=""
                class="single-input"
              />
            </div>

            <!-- username -->
            <div class="mt-10">
              <input
                type="text"
                name="username"
                placeholder="Username"
                onfocus="this.placeholder = ''"
                onblur="this.placeholder = 'Username'"
                required=""
                class="single-input"
              />
            </div>

            <!-- email -->
            <div class="mt-10">
              <input
                type="email"
                name="email"
                placeholder="Email"
                onfocus="this.placeholder = ''"
                onblur="this.placeholder = 'Email'"
                required=""
                class="single-input"
              />
            </div>

            <!-- password1 -->
            <div class="mt-10">
              <input
                type="password"
                name="password1"
                placeholder="Password"
                onfocus="this.placeholder = ''"
                onblur="this.placeholder = 'Password'"
                required=""
                class="single-input"
              />
            </div>

            <!-- confirm password -->
            <div class="mt-10">
              <input
                type="password"
                name="password2"
                placeholder="Confrim Password"
                onfocus="this.placeholder = ''"
                onblur="this.placeholder = 'Confrim Password'"
                required=""
                class="single-input"
              />
            </div>

            <!-- submit button -->
            <input
              type="submit"
              value="Register"
              class="genric-btn success-border circle"
              style="margin-top: 1rem"
            />
          </form>
          <!-- end form -->
        </div>
      </div>
      <div class="col-lg-4">{% include 'right-sidebar.html' %}</div>
    </div>
  </div>
</section>
<!--================Blog Area =================-->

{% endblock %}

templates/users/user-list.html
{% extends "base.html" %}

<!--  -->

{% load static %}

<!--  -->

{% block content %}

<!--================Home Banner Area =================-->
<section class="banner_area">
  <div class="banner_inner d-flex align-items-center">
    <div class="overlay bg-parallax" data-stellar-ratio="0.9" data-stellar-vertical-offset="0" data-background=""></div>
    <div class="container">
      <div class="banner_content text-center">
        <h2>Users List</h2>
        <div class="page_link">
          <a href="{% url 'index' %}">Home</a>
        </div>
      </div>
    </div>
  </div>
</section>
<!--================End Home Banner Area =================-->

<!--================Blog Area =================-->
<section class="blog_area p_120">
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
        <div class="blog_left_sidebar" style="text-align: center">
          <!-- posts -->
          {% for profile in profiles %}
          <div class="container" style="border: 2px solid green; margin-bottom: 16px; padding: 1rem">
            <img src="{{ profile.image.url }}" alt="" />
            <a href="{% url 'users:user_posts' pk=profile.user.id %}"><h4>{{ profile.user.username }}</h4></a>
            <p>{{ profile.birth_day }}</p>
            <p>{{ profile.bio }}</p>
          </div>
          {% endfor %}
          <!-- end posts -->

          <!-- pagination -->
          {% if is_paginated %}
          <nav class="blog-pagination justify-content-center d-flex">
            <ul class="pagination">
              <!-- previous -->
              {% if page_obj.has_previous %}
              <li class="page-item">
                <a href="?page={{page_obj.previous_page_number}}" class="page-link" aria-label="Previous">
                  <span aria-hidden="true">
                    <span class="lnr lnr-chevron-left"></span>
                  </span>
                </a>
              </li>
              {% else %}
              <li class="page-item disabled">
                <a href="#" class="page-link" aria-label="Previous">
                  <span aria-hidden="true">
                    <span class="lnr lnr-chevron-left"></span>
                  </span>
                </a>
              </li>
              {% endif %}
              <!-- end previous -->

              <!-- pages -->
              {% for i in paginator.page_range%}
              <!--  -->
              {% if page_obj.number == i %}
              <li class="page-item active">
                <a href="#" class="page-link">{{ i }}</a>
              </li>
              {% else %}

              <li class="page-item">
                <a href="?page={{i}}" class="page-link">{{ i }}</a>
              </li>
              {% endif %}
              <!--  -->
              {% endfor %}
              <!-- end pages -->

              <!-- next page -->
              {% if page_obj.has_next %}
              <li class="page-item">
                <a href="?page={{page_obj.next_page_number}}" class="page-link" aria-label="Next">
                  <span aria-hidden="true">
                    <span class="lnr lnr-chevron-right"></span>
                  </span>
                </a>
              </li>
              {% else %}
              <li class="page-item disabled">
                <a href="#" class="page-link" aria-label="Next">
                  <span aria-hidden="true">
                    <span class="lnr lnr-chevron-right"></span>
                  </span>
                </a>
              </li>
              {% endif %}
              <!-- end next page -->
            </ul>
          </nav>
          {% endif %}
          <!-- end pagination -->
        </div>
      </div>
      <div class="col-lg-4">{% include 'right-sidebar.html' %}</div>
    </div>
  </div>
</section>
<!--================Blog Area =================-->

{% endblock %}

templates/users/user-post.html
{% extends "base.html" %}

<!--  -->

{% load static %}

<!--  -->

{% block content %}

<!--================Home Banner Area =================-->
<section class="banner_area">
  <div class="banner_inner d-flex align-items-center">
    <div class="overlay bg-parallax" data-stellar-ratio="0.9" data-stellar-vertical-offset="0" data-background=""></div>
    <div class="container">
      <div class="banner_content text-center">
        <h2>User Posts</h2>
        <div class="page_link">
          <a href="{% url 'index' %}">Home</a>
        </div>
      </div>
    </div>
  </div>
</section>
<!--================End Home Banner Area =================-->

<!--================Blog Area =================-->
<section class="blog_area p_120">
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
        <div class="blog_left_sidebar">
          <!-- posts -->
          {% for post in posts %}
          <article class="blog_style1">
            <div class="blog_img">
              <img class="img-fluid" src="{{post.image.url}}" alt="" />
            </div>
            <div class="blog_text">
              <div class="blog_text_inner">
                {% for tag in post.tag.all %}
                <a class="cat" href="{% url 'tag_detail' slug=tag.slug %}">{{tag.title}}</a>
                {% endfor %}
                <a href="{% url 'detail' pk=post.id slug=post.slug %}"><h4>{{post.title}}</h4></a>
                <p>{{post.content|truncatechars:150}}</p>
                <div class="date">
                  <a href="#"
                    ><i class="fa fa-calendar" aria-hidden="true"></i>
                    {{post.publishing_date}}
                  </a>
                  <a href="#"><i class="fa fa-comments-o" aria-hidden="true"></i> 05</a>
                </div>
              </div>
            </div>
          </article>
          {% endfor %}
          <!-- end posts -->

          <!-- pagination -->
          {% if is_paginated %}
          <nav class="blog-pagination justify-content-center d-flex">
            <ul class="pagination">
              <!-- previous -->
              {% if page_obj.has_previous %}
              <li class="page-item">
                <a href="?page={{page_obj.previous_page_number}}" class="page-link" aria-label="Previous">
                  <span aria-hidden="true">
                    <span class="lnr lnr-chevron-left"></span>
                  </span>
                </a>
              </li>
              {% else %}
              <li class="page-item disabled">
                <a href="#" class="page-link" aria-label="Previous">
                  <span aria-hidden="true">
                    <span class="lnr lnr-chevron-left"></span>
                  </span>
                </a>
              </li>
              {% endif %}
              <!-- end previous -->

              <!-- pages -->
              {% for i in paginator.page_range%}
              <!--  -->
              {% if page_obj.number == i %}
              <li class="page-item active">
                <a href="#" class="page-link">{{ i }}</a>
              </li>
              {% else %}

              <li class="page-item">
                <a href="?page={{i}}" class="page-link">{{ i }}</a>
              </li>
              {% endif %}
              <!--  -->
              {% endfor %}
              <!-- end pages -->

              <!-- next page -->
              {% if page_obj.has_next %}
              <li class="page-item">
                <a href="?page={{page_obj.next_page_number}}" class="page-link" aria-label="Next">
                  <span aria-hidden="true">
                    <span class="lnr lnr-chevron-right"></span>
                  </span>
                </a>
              </li>
              {% else %}
              <li class="page-item disabled">
                <a href="#" class="page-link" aria-label="Next">
                  <span aria-hidden="true">
                    <span class="lnr lnr-chevron-right"></span>
                  </span>
                </a>
              </li>
              {% endif %}
              <!-- end next page -->
            </ul>
          </nav>
          {% endif %}
          <!-- end pagination -->
        </div>
      </div>
      <div class="col-lg-4">{% include 'right-sidebar.html' %}</div>
    </div>
  </div>
</section>
<!--================Blog Area =================-->

{% endblock %}